// <auto-generated>
//     Generated by pipeline/codegen.py from the FastAPI OpenAPI schema.
//     Edit the Pydantic models in pipeline/api.py, not this file.
// </auto-generated>

public static class CyberContract {
    public const string DefaultView = "attack_by_year";
    public const int FirstYear = 2004;
    public const int LastYear = 2024;

    public const int LimitMinimum = 1;
    public const int LimitMaximum = 200;
    public const int LimitDefault = 100;
    public const int PerDefault = 10;
    public const int BreachLimitDefault = 10;
    public const int BreachLimitMaximum = 50;

    public static readonly string[] Views = { "attack_by_year", "industry_by_attack", "before_after" };
    public static readonly string[] Industries = { "Agriculture", "Mining", "Construction", "Manufacturing", "Transportation & Public Utilities", "Wholesale Trade", "Retail Trade", "Finance, Insurance, Real Estate", "Services", "Public Administration" };
    public static readonly string[] AttackTypes = { "Unauthorized Access", "Malware", "Ransomware", "Phishing", "Misconfiguration", "Credential Stuffing", "Not Disclosed" };
    public static readonly string[] InformationTypes = { "Personal", "Financial", "Other", "Not Disclosed" };
    public static readonly string[] InformationAccessed = { "Name", "SSN", "Address", "Email", "Phone Number", "Credit Card", "Debit Card", "Bank Account", "Password", "User Name", "Intellectual Property", "Other", "Not Disclosed" };
    public static readonly string[] Relationships = { "Parent", "Subsidiary / Affiliate" };
    public static readonly string[] Regions = { "US Mid Atlantic", "US New England", "US Southeast", "US Midwest", "US Southwest", "US West", "Canada", "Foreign" };
    public static readonly string[] Markets = { "NYSE", "NYSE MKT", "NASDAQ Global Select Market", "NASDAQ Global Market", "NASDAQ Capital Market", "OTCQX U.S.", "OTCQX International", "OTCQX International Premier", "OTCQB", "Pink Current", "Pink Limited", "Expert Market" };
    public static readonly string[] Countries = { "United States", "United Kingdom", "Japan", "Canada", "Ireland", "Brazil", "Netherlands", "India", "Bermuda", "Luxembourg", "China", "Cayman Islands", "Mexico", "Germany", "Argentina", "Taiwan", "South Africa", "Italy", "Israel", "Belgium", "Finland", "Cyprus", "South Korea", "Hong Kong", "Singapore", "Colombia", "Indonesia", "Spain", "Denmark", "Switzerland", "Panama" };
}
