"""Emit the C# side of the API contract from the FastAPI OpenAPI schema.

The Unity tools would otherwise repeat the API's constraints by hand: a year
range against Field(ge=..., le=...), an attack type against ATTACK_TYPES. Both
come from one source here, and test_codegen.py fails if the checked-in file
drifts from what this produces.

    python codegen.py            rewrite the generated file
    python codegen.py --check    exit non-zero if it is stale
"""

import argparse
import sys
from pathlib import Path

TARGET = Path(__file__).resolve().parents[1] / "Assets/Source/Gemini/Tools/CyberContract.g.cs"

HEADER = """// <auto-generated>
//     Generated by pipeline/codegen.py from the FastAPI OpenAPI schema.
//     Edit the Pydantic models in pipeline/api.py, not this file.
// </auto-generated>

public static class CyberContract {
"""

# The filters that take names, by the C# name of the list holding them.
ENUMS = {
    "Views": "ViewName",
    "Industries": "DivisionName",
    "AttackTypes": "AttackType",
    "InformationTypes": "InformationType",
    "InformationAccessed": "Accessed",
    "Relationships": "Relationship",
    "Regions": "RegionName",
    "Markets": "MarketName",
    "Countries": "CountryName",
}


def schema():
    import api

    return api.app.openapi()


def parameters(document, path, method="get"):
    return {p["name"]: p["schema"] for p in document["paths"][path][method]["parameters"]}


def csharp_array(name, values):
    body = ", ".join(f'"{v}"' for v in values)
    return f"    public static readonly string[] {name} = {{ {body} }};\n"


def csharp_int(name, value):
    return f"    public const int {name} = {value};\n"


def render(document):
    sheet = parameters(document, "/sheet")
    breaches = parameters(document, "/breaches")
    schemas = document["components"]["schemas"]

    out = [HEADER]
    out.append(f'    public const string DefaultView = "{sheet["view"]["default"]}";\n')
    out.append(csharp_int("FirstYear", sheet["since"]["minimum"]))
    out.append(csharp_int("LastYear", sheet["until"]["maximum"]))
    out.append("\n")
    out.append(csharp_int("LimitMinimum", sheet["limit"]["minimum"]))
    out.append(csharp_int("LimitMaximum", sheet["limit"]["maximum"]))
    out.append(csharp_int("LimitDefault", sheet["limit"]["default"]))
    out.append(csharp_int("PerDefault", sheet["per"]["default"]))
    out.append(csharp_int("BreachLimitDefault", breaches["limit"]["default"]))
    out.append(csharp_int("BreachLimitMaximum", breaches["limit"]["maximum"]))
    out.append("\n")
    for name, component in ENUMS.items():
        out.append(csharp_array(name, schemas[component]["enum"]))
    out.append("}\n")
    return "".join(out)


def write_or_check(target, generated):
    """The command line of a script that generates a checked-in file: rewrite
    the file, or with --check, exit non-zero if it differs from what the script
    generates now. gateway.py shares it."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if args.check:
        current = target.read_text() if target.exists() else ""
        if current != generated:
            print(f"{target} is stale; run: python {Path(sys.argv[0]).name}", file=sys.stderr)
            return 1
        print(f"{target} is up to date")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated)
    print(f"wrote {target}")
    return 0


def main():
    return write_or_check(TARGET, render(schema()))


if __name__ == "__main__":
    sys.exit(main())
